build tests

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,10 +1,8 @@
 #!/usr/bin/env bash
 # bin/compile <build-dir> <cache-dir> <env-dir>
 
-# fail hard
-set -o pipefail
-# fail harder
-set -eu
+# fail fast
+set -e
 
 export CWD=$(cd $(dirname $0)/; pwd)
 export APP_DIR=/app
@@ -34,6 +32,12 @@ curl --retry 3 --silent --location $JVM_COMMON_BUILDPACK | tar xzm -C /tmp/jvm-c
 . /tmp/jvm-common/bin/java
 . /tmp/jvm-common/opt/jdbc.sh
 install_java_with_overlay ${BUILD_DIR}
+
+
+# fail hard from this point on
+set -o pipefail
+# fail harder
+set -eu
 
 mkdir -p $CACHE_DIR
 
